disabled_rules:
- line_length
- force_cast
- identifier_name
- type_name
- type_body_length
- file_length
- cyclomatic_complexity
- function_body_length
- function_parameter_count
- large_tuple
- multiple_closures_with_trailing_closure
- unused_optional_binding
- valid_ibinspectable
- implicit_getter
- notification_center_detachment
- no_fallthrough_only
- vertical_parameter_alignment
- nesting
- compiler_protocol_init
- legacy_random
- class_delegate_protocol
- todo
- void_function_in_ternary
- closure_parameter_position
- discarded_notification_center_observer
- weak_delegate
opt_in_rules:
- empty_count
- empty_string
excluded:
- Pods
- script
reporter: "xcode"
