//
//  LandingViewModel.swift
//  Onews
//
//  Created by Sizwe Khathi on 2023/03/25.
//

import Foundation
import UIKit

struct LandingViewModel {
    
    static let shared = LandingViewModel()
    
    var articlesArray: [NewsArticleModel] =
    [
        NewsArticleModel(articleTitle: "7 dead in 'destructive' Mississippi tornado, official says - ABC News", articleDescription: "A deadly tornado touched down in Mississippi, officials said.",articleURL: "https://abcnews.go.com/US/7-dead-mississippi-tornado-official/story?id=98117564",articleImgURL: "https://s.abcnews.com/images/US/mississipppi-tornado_1679721477403_hpMain_16x9_992.jpg",articleAuthor: "Will McDuffie",articleContent: "At least seven people died in a \"destructive\" tornado that rolled across Mississippi late Friday, leaving a trail of damage for more than 100 miles, local and federal authorities said.\r\nSearch and re… [+1791 chars]", publishedDate: "2023-05-21T19:15:11Z", articleSource: Source(id: "abc-news", name: "ABC News")),
    NewsArticleModel(articleTitle: "Intel co-founder Gordon Moore dies at 94 - Fox Business", articleDescription: "Gordon Moore, the man who co-founded the technology giant Intel, has died at the age of 94. Moore died peacefully his home in Hawaii surrounded by family.", articleURL: "https://www.foxbusiness.com/technology/intel-co-founder-gordon-moore-dies-at-94", articleImgURL: "https://a57.foxnews.com/static.foxbusiness.com/foxbusiness.com/content/uploads/2023/03/0/0/Intel-Moore-A.jpg?ve=1&tl=1", articleAuthor: "Ken Martin", articleContent: "Intel's co-founder Gordon Moore died on Friday at the age of 94.\r\nThe announcement was made in a statement from Intel and the Gordon and Betty Moore Foundation.\r\nThe foundation reported he died peace… [+4477 chars]", publishedDate: "2023-05-21T07:15:11Z", articleSource: Source(id: nil, name: "Fox Business")),
    NewsArticleModel(articleTitle: "Texas police: Migrants found 'suffocating' in train; 2 dead - CBS TEXAS", articleDescription: "Police in South Texas said Friday that two migrants were found dead and at least 10 were hospitalized after authorities received a call that they were \"suffo...", articleURL: "https://www.youtube.com/watch?v=Rj4hy-gdyhs", articleImgURL: "https://i.ytimg.com/vi/Rj4hy-gdyhs/maxresdefault.jpg", articleAuthor: nil, articleContent: nil, publishedDate: "2023-03-21T19:15:11Z", articleSource: Source(id: nil, name: "YouTube")),
    NewsArticleModel(articleTitle: "Officials: 2 dead, 9 unaccounted for in Reading chocolate factory explosion - FOX 29 Philadelphia", articleDescription: "An explosion at a historic Reading chocolate factory left two people dead and several others hurt, according to officials.", articleURL: "https://www.fox29.com/news/watch-building-explosion-in-reading-triggers-multi-alarm-fire", articleImgURL: "https://images.foxtv.com/static.fox29.com/www.fox29.com/content/uploads/2023/03/1280/720/Reading-Explosion_New.jpg?ve=1&tl=1", articleAuthor: "FOX 29 Philadelphia", articleContent: "READING, Pa. - An explosion at a historic Reading chocolate factory left two people dead and several others hurt, according to officials. \r\nFirefighters responded to R.M. Palmer Company on South 2nd … [+1133 chars]", publishedDate: "2023-02-21T19:15:11Z", articleSource: Source(id: nil, name: "FOX 29 News Philadelphia")),
    NewsArticleModel(articleTitle: "Utah's Jenna Johnson rues missed FTs in LSU loss, but will 'get back after it' - ESPN India", articleDescription: "LSU's Alexis Morris made all four of her late free throws but Utah's Jenna Johnson -- a 72.8% free throw shooter -- missed both of hers, and the Tigers reached the Elite Eight for the first time since 2008 after beating the Utes 66-63 on Friday night.", articleURL: "https://www.espn.in/womens-college-basketball/story/_/id/35938083/utah-jenna-johnson-rues-missed-fts-lsu-loss-get-back-it", articleImgURL: "https://a2.espncdn.com/combiner/i?img=%2Fphoto%2F2023%2F0325%2Fr1149721_1296x729_16%2D9.jpg", articleAuthor: "M.A. Voepel", articleContent: "GREENVILLE, S.C. -- The NCAA tournament puts players into the most pressure-packed situations of their careers. It happened to two players in the final 10 seconds of No. 3 seed LSU's66-63 win over No… [+3956 chars]", publishedDate: "2023-03-27T19:15:11Z", articleSource: Source(id: nil, name: "ESPN India")),
    NewsArticleModel(articleTitle: "US charges suspected Russian spy who allegedly used fake identity to enter US, gather info from American citizens - CNN", articleDescription: "The Justice Department announced charges Friday against a Russian national who allegedly entered the United States under a fake identity and gathered information from American citizens about the then-looming Russian invasion of Ukraine.", articleURL: "https://www.cnn.com/2023/03/24/politics/russian-spy-us-graduate-student/index.html", articleImgURL: "https://media.cnn.com/api/v1/images/stellar/prod/221219134238-fbi-seal-file.jpg?c=16x9&q=w_800,c_fill", articleAuthor: "Hannah Rabinowitz", articleContent: "The Justice Department announced charges Friday against a Russian national who allegedly entered the United States under a fake identity and gathered information from American citizens about the then… [+3654 chars]", publishedDate: "2023-03-21T19:15:11Z", articleSource: Source(id: "cnn", name: "CNN")),
    NewsArticleModel(articleTitle: "Miami upsets Houston to advance to Elite 8, no more No. 1 seeds remain in March Madness - Fox News", articleDescription: "For the first time in March Madness history, the Elite 8 will be without a No. 1 seed, as the Miami Hurricanes knocked out the last one standing on Friday.", articleURL: "https://www.foxnews.com/sports/miami-upsets-houston-advance-elite-8-no-more-1-seeds-remain-march-madness", articleImgURL: "https://static.foxnews.com/foxnews.com/content/uploads/2023/03/miami-canes.jpg", articleAuthor: "Associated Press", articleContent: "Nijel Pack and Miami hit shots from near and far against the stingiest defense in the country to beat Houston 89-75 on Friday night in the Sweet 16, leaving the NCAA Tournament without a single No. 1… [+3748 chars]", publishedDate: "2023-02-21T19:15:11Z", articleSource: Source(id: "fox-news", name: "Fox News")),
    NewsArticleModel(articleTitle: "Syria attacks: Biden warns Iran US will 'act forcefully' to protect Americans - The Guardian", articleDescription: "US president says he does not seek conflict with Iran but warns of consequences as Tehran-backed forces and US personnel launch attacks", articleURL: "https://www.theguardian.com/world/2023/mar/25/syria-biden-warns-iran-us-will-act-forcefully-to-protect-americans", articleImgURL: "https://i.guim.co.uk/img/media/9ecf6a656d14b41336b0b0e3a427d66069b64541/0_52_3463_2078/master/3463.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=e4462bfe6462ed4787d5df5b0356ce04", articleAuthor: "Guardian staff reporter", articleContent: "President Joe Biden has warned Iran that the United States will act forcefully to protect Americans, after the US military carried out air strikes against Iran-backed forces in retaliation for an att… [+3332 chars]", publishedDate: "2023-04-22T19:15:11Z", articleSource: Source(id: nil, name: "The Guardian")),
    NewsArticleModel(articleTitle: "Early Alzheimer’s disease could be diagnosed through eye exams, new study suggests - Fox News", articleDescription: "Researchers at Cedars-Sinai in Los Angeles have found the human eye can show early signals of Alzheimer's disease long before symptoms of dementia become apparent, according to a study.", articleURL: "https://www.foxnews.com/health/early-alzheimers-disease-diagnosed-eye-exams-study-suggests", articleImgURL: "https://static.foxnews.com/foxnews.com/content/uploads/2021/03/iStock-108220711.jpg", articleAuthor: "Melissa Rudy", articleContent: "Alzheimers is a disease of the brain, usually diagnosed through MRI scans and a battery of other tests. \r\nResearchers, however, have found that the human eye can show early signals of this common for… [+3075 chars]", publishedDate: "2023-02-22T19:15:11Z", articleSource: Source(id: "fox-news", name: "Fox News")),
    NewsArticleModel(articleTitle: "Former Trump admin officials must testify before grand jury in 2020 election inquiry, federal judge says - Fox News", articleDescription: "Former Trump administration officials cannot invoke executive privilege to avoid testifying before a grand jury, a federal judge ruled Friday.", articleURL: "https://www.foxnews.com/politics/former-trump-admin-officials-must-testify-grand-jury-2020-election-inquiry-federal-judge-says", articleImgURL: "https://static.foxnews.com/foxnews.com/content/uploads/2022/11/GettyImages-1440141408.jpg", articleAuthor: "Louis Casiano", articleContent: "A federal judge on Friday said that several former officials in the Trump administration, including his former chief of staff, Mark Meadows, must testify in a 2020 election inquiry. \r\nThe ruling by J… [+1403 chars]", publishedDate: "2023-04-21T19:15:11Z", articleSource: Source(id: "fox-news", name: "Fox News")),
    NewsArticleModel(articleTitle: "Gwyneth Paltrow trial – live: Actor tells court she initially thought skiing accident was ‘sexual assault’ - The Independent", articleDescription: "Goop founder faces civil lawsuit regarding 2016 skiing accident involving retired optometrist Terry Sanderson at Deer Valley resort", articleURL: "https://www.independent.co.uk/news/world/americas/gwyneth-paltrow-ski-accident-trial-live-b2307409.html", articleImgURL: "https://static.independent.co.uk/2023/03/24/05/Gwyneth_Paltrow_Skiing_Lawsuit_33091.jpg?quality=75&width=1200&auto=webp", articleAuthor: "Andrea Blanco", articleContent: "Sign up to our Evening Headlines email for your daily guide to the latest news\r\nSign up to our free US Evening Headlines email\r\nGwyneth Paltrow says she briefly thought a 2016 ski collision was in fa… [+7481 chars]", publishedDate: "2023-04-21T19:15:11Z", articleSource: Source(id: "independent", name: "Independent")),
    NewsArticleModel(articleTitle: "San Diego State ousts top overall seed Alabama to reach Elite Eight - ESPN", articleDescription: "Fifth-seeded San Diego State upset top overall seed Alabama on Friday to clinch the program's first-ever berth in the Elite Eight.", articleURL: "https://www.espn.com/mens-college-basketball/story/_/id/35937403/san-diego-state-ousts-top-overall-seed-alabama-reach-elite-eight", articleImgURL: "https://a2.espncdn.com/combiner/i?img=%2Fphoto%2F2023%2F0325%2Fr1149690_1296x729_16%2D9.jpg", articleAuthor: "Pete Thamel", articleContent: "LOUISVILLE, KY. -- No. 1 overall seed Alabama, which emerged as the most dominant and divisive team during a turbulent 2022-23 season, sputtered offensively and found an exit from the NCAA tournament… [+7077 chars]", publishedDate: "2023-02-27T19:15:11Z", articleSource: Source(id: nil, name: "ESPN"))]
}



